#!/bin/bash

description=$1
date=$(date +%Y%m%d)

latest=$(find ./migrations -name "${date}_*.sql" | sort -r | head -n1 | grep -oE "${date}_[0-9]{2}" | cut -d'_' -f2)

if [ -z "$latest" ]; then
  seq="01"
else
  seq=$(printf "%02d" $((10#$latest + 1)))
fi

filename="migrations/${date}_${seq}_${description}.sql"
touch $filename

echo "Created migration file: $filename"
