name: API - Build & Deploy Production

env:
  AZURE_WEBAPP_NAME: ga-cd-lab-api
  AZURE_WEBAPP_PACKAGE_PATH: "api"
  DOTNET_VERSION: "9"
  # for testing purposes only -> will be stored & retrieved from az key vault in the future
  DB_CONNECTION_STRING: "Server=tcp:ga-cd-lab-sql.database.windows.net,1433;Initial Catalog=ga-cd-lab-db;Persist Security Info=False;User ID=sqladmin;Password=P@ssw0rd1234!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

on:
  workflow_dispatch:
    # Manual trigger only, as per requirements

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
        working-directory: ./.infrastructure
      - name: Terraform Plan
        run: terraform plan -var-file=environments/prod.tfvars -out=tfplan
        working-directory: ./.infrastructure
        env:
          TF_VAR_azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      # For production, we keep the apply step for manual review
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./.infrastructure
        env:
          TF_VAR_azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  database-migration:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build database migration project
        run: dotnet build dbup --configuration Release

      # For production, generate script first for review
      - name: Generate migration script
        run: dotnet run --project dbup/dbup.csproj -- --scriptsonly --output=./migration-script.sql --environment=prod
        env:
          DB_CONNECTION_STRING: ${{ env.DB_CONNECTION_STRING }}

      - name: Upload migration script artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-migration-script
          path: ./migration-script.sql

      # Run migrations only after review (through manual workflow trigger)
      - name: Run database migrations
        id: run_migrations
        run: |
          dotnet run --project dbup/dbup.csproj -- --environment=prod
          echo "MIGRATION_SUCCESS=true" >> $GITHUB_ENV
        env:
          DB_CONNECTION_STRING: ${{ env.DB_CONNECTION_STRING }}
        continue-on-error: true

      - name: Check migration result
        if: steps.run_migrations.outcome == 'failure'
        run: |
          echo "::error::Database migration failed in PRODUCTION. Check logs for details."
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: [terraform, database-migration]
    if: needs.terraform.result == 'success' && needs.database-migration.result == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build with dotnet
        run: dotnet build api --configuration Release
      - name: dotnet publish
        run: dotnet publish api -c Release -r linux-x64 -o ${{env.DOTNET_ROOT}}/api
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/api

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROD_API_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
