name: Update Azure Credentials
on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Get Azure Service Principal Credentials
        id: azure-credentials
        run: |
          SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')
          CLIENT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')
          CLIENT_SECRET=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')
          TENANT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.tenantId')
          
          echo "ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$CLIENT_SECRET" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$TENANT_ID" >> $GITHUB_ENV
      
      - name: Terraform Init
        run: |
          cd .infrastructure
          terraform init
        env:
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
      
      - name: Terraform Apply
        run: |
          cd .infrastructure
          terraform apply -auto-approve
        env:
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
      
      - name: Update GitHub Secrets
        run: |
          cd .infrastructure
          CLIENT_ID=$(terraform output -raw client_id)
          CLIENT_SECRET=$(terraform output -raw client_secret)
          TENANT_ID=$(terraform output -raw tenant_id)
          SUBSCRIPTION_ID=$(terraform output -raw subscription_id)
          
          gh secret set AZURE_CLIENT_ID --body "$CLIENT_ID"
          gh secret set AZURE_CLIENT_SECRET --body "$CLIENT_SECRET"
          gh secret set AZURE_TENANT_ID --body "$TENANT_ID"
          gh secret set AZURE_SUBSCRIPTION_ID --body "$SUBSCRIPTION_ID"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
