name: Update Azure Credentials

on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Update GitHub Secrets
        run: |
          CLIENT_ID=$(terraform output -raw client_id)
          CLIENT_SECRET=$(terraform output -raw client_secret)
          TENANT_ID=$(terraform output -raw tenant_id)
          SUBSCRIPTION_ID=$(terraform output -raw subscription_id)
          
          gh secret set AZURE_CLIENT_ID --body "$CLIENT_ID"
          gh secret set AZURE_CLIENT_SECRET --body "$CLIENT_SECRET"
          gh secret set AZURE_TENANT_ID --body "$TENANT_ID"
          gh secret set AZURE_SUBSCRIPTION_ID --body "$SUBSCRIPTION_ID"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
